### ISSUE TITLE
[FEATURE REQUEST] Add Some Feature

### ISSUE THREAD

**Issue by coolerspeex** [BytePhoenixCoding/BlockchainTokenSniper#25]
Features : 
----------------------
- Take Profit / Stop loss
- Trailing stop 
- Twitter Scraper
- Simulated transaction mode
- Tax checker
- Multiwallet
- Sniper liquidity 
- Sniper liquidity after DxSale
- Sniper antibot tokens
- Sniper Telegram
- Trading mode / Pump bot mode
- Auto Approve tokens
- Price/Profit live stream
- Take Profit / Stop Loss
- Trailing stop
- Sell in instant with hotkeys
- Rebuy dip
- Simulated transactions mode to avoid loss of gas
- Rug SHIELD
- Honeypot SHIELD
- High tax SHIELD
- Support PancakeSwap / ApeSwap / Uniswap / Koffeeswap

**Comment by BytePhoenixData** [comment]
Thanks for the suggestions, will keep in mind

**Comment by Nisthar** [comment]
@coolerspeex hey do you have discord to have a discussion on this?

**Comment by BlockchainTokenSniper** [comment]
> @coolerspeex hey do you have discord to have a discussion on this?

everything is in telegram, link is in readme

**Comment by BlockchainTokenSniper** [comment]
Take Profit / Stop loss - autosell at specific profit amount eg. 2x white_check_mark
Trailing stop
Twitter Scraper
Simulated transaction mode - rugdoc is implemented which does that white_check_mark
Tax checker - rugdoc only allows low tax (under 10% I think) white_check_mark
Multiwallet
Sniper liquidity - detects liquidity amount white_check_mark
Sniper liquidity after DxSale white_check_mark
Sniper antibot tokens - antibot delay implemented for specific number of seconds white_check_mark
Sniper Telegram - main telegram and testing telegram is available white_check_mark
Trading mode / Pump bot mode
Auto Approve tokens - tokens are approved right before selling white_check_mark
Price/Profit live stream white_check_mark
Take Profit / Stop Loss white_check_mark
Trailing stop
Sell in instant with hotkeys white_check_mark
Rebuy dip
Simulated transactions mode to avoid loss of gas white_check_mark
Rug SHIELD - rugpull detection is in progress
Honeypot SHIELD white_check_mark
High tax SHIELD white_check_mark
Support PancakeSwap / ApeSwap / Uniswap / Koffeeswap
